In [17]:
#Problem Statement 1: Write a function so that the columns of the output matrix are powers of the input vector. 
#The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False,
#the i-th output column is the input vector raised element-wise to the power of N - i - 1.
# Import numpy module to access methodsn and fucntion for array/matrix


import numpy as num_py
def matrix_Vandermonde(input_vector,n,bool_arg):
    output_matrix=num_py.vander(x=input_vector,N=n,increasing=bool_arg)
    return output_matrix
input_vector = num_py.arange(5,13,2)   
n = 5       
bool_arg_T = True                     
bool_arg_F = False                    

out_matrix_True=matrix_Vandermonde(input_vector,n,bool_arg_T)

out_matrix_False=matrix_Vandermonde(input_vector,n,bool_arg_F)

print("Input vector \n",input_vector,"\n")
print("Output Matrix , when boolean argument is True: \n",out_matrix_True,"\n")
print("Output Matrix , when boolean argument is False: \n",out_matrix_False)


Input vector 
 [ 5  7  9 11] 

Output Matrix , when boolean argument is True: 
 [[    1     5    25   125   625]
 [    1     7    49   343  2401]
 [    1     9    81   729  6561]
 [    1    11   121  1331 14641]] 

Output Matrix , when boolean argument is False: 
 [[  625   125    25     5     1]
 [ 2401   343    49     7     1]
 [ 6561   729    81     9     1]
 [14641  1331   121    11     1]]


In [22]:
# write a function to find moving average in an array over a window:
#TEST it OVER[3,5,7,2,8, 10, 11, 65, 72, 81, 99, 100, 150] and of 3.

#Solution

import numpy as num_py
def moving_average_seq(input_array,k):
    val_array=num_py.cumsum(input_array,dtype=float)    
    val_array[3:]=val_array[3:]-val_array[:-3]
    return val_array[3-1:]/3
lst =[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
input_array = num_py.array(lst)
# output 
# Thus, total movieng average sequence are 13-3+1 = 11 values  ; where n=13 , k=3
output_array=moving_average_seq(input_array,k=3)
print("Input: M.average of values",lst,"are:\n")
print("Output:\n",output_array)

Input: M.average of values [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] are:

Output:
 [  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
